service: aws-nodejs
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
#  region: ap-northeast-1

plugins:
  - serverless-offline
functions:
  lineWebhook:
    handler: line.webhook
    events:
      - http:
          path: line/webhook
          method: post
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
